apiVersion: v1
kind: Service
metadata:
  name: alertnotifiersystem
  namespace: dsbd-namespace
spec:
  selector:
    app: alertnotifiersystem
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
