apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertsystem-deployment
  namespace: dsbd-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertsystem
  template:
    metadata:
      labels:
        app: alertsystem
    spec:
      containers:
        - name: alertsystem
          image: cp_alertsystem:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: "db"
            - name: DB_USER
              value: "myuser"
            - name: DB_PASSWORD
              value: "mypassword"
            - name: DB_NAME
              value: "dsbd_db"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8000 # se esponi metrics allo stesso modo
