apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-deployment
  namespace: dsbd-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert
  template:
    metadata:
      labels:
        app: alert
    spec:
      containers:
        - name: alertsystem
          image: cp_alertsystem:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: "db"
            - name: DB_USER
              value: "myuser"
            - name: DB_PASSWORD
              value: "mypassword"
            - name: DB_NAME
              value: "dsbd_db"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8000 # se esponi metrics allo stesso modo
        - name: alertnotifiersystem
          image: c_alertnotifiersystem:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: "db"
            - name: DB_USER
              value: "myuser"
            - name: DB_PASSWORD
              value: "mypassword"
            - name: DB_NAME
              value: "dsbd_db"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8001 # se esponi metrics allo stesso modo
---
apiVersion: v1
kind: Service
metadata:
  name: alert
  namespace: dsbd-namespace
spec:
  selector:
    app: alert
  ports:
    - name: alertsystem-metric
      port: 8000
      targetPort: 8000
    - name: alertnotifiersystem-metrics
      port: 8001
      targetPort: 8001