apiVersion: v1
kind: Service
metadata:
  name: data-collector
  namespace: dsbd-namespace
spec:
  selector:
    app: data-collector
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
