apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collector-deployment
  namespace: dsbd-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collector
  template:
    metadata:
      labels:
        app: data-collector
    spec:
      containers:
        - name: data-collector
          image: data-collector:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: "db"
            - name: DB_USER
              value: "myuser"
            - name: DB_PASSWORD
              value: "mypassword"
            - name: DB_NAME
              value: "dsbd_db"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8000 # metrics
