apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-deployment
  namespace: dsbd-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
        - name: grpc-server
          image: grpc-server:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: "db"
            - name: DB_USER
              value: "myuser"
            - name: DB_PASSWORD
              value: "mypassword"
            - name: DB_NAME
              value: "dsbd_db"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 18072
            - containerPort: 8000 # metrics
