FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY server/server.py dsbd.proto database.py ./ 
COPY handlers /app/handlers
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. dsbd.proto


# Espone la porta del server gRPC
EXPOSE 18072
# Espone la porta per le metriche Prometheus (se è 8000)
EXPOSE 8000

CMD ["python", "server.py"]
